export const speechToTextLanguages: {[key: string]: string} = {
    'Afrikaans (South Africa)': 'af-ZA',
    'Albanian (Albania)': 'sq-AL',
    'Amharic (Ethiopia)': 'am-ET',
    'Arabic (Algeria)': 'ar-DZ',
    'Arabic (Bahrain)': 'ar-BH',
    'Arabic (Egypt)': 'ar-EG',
    'Arabic (Iraq)': 'ar-IQ',
    'Arabic (Israel)': 'ar-IL',
    'Arabic (Jordan)': 'ar-JO',
    'Arabic (Kuwait)': 'ar-KW',
    'Arabic (Lebanon)': 'ar-LB',
    'Arabic (Mauritania)': 'ar-MR',
    'Arabic (Morocco)': 'ar-MA',
    'Arabic (Oman)': 'ar-OM',
    'Arabic (Qatar)': 'ar-QA',
    'Arabic (Saudi Arabia)': 'ar-SA',
    'Arabic (State of Palestine)': 'ar-PS',
    'Arabic (Tunisia)': 'ar-TN',
    'Arabic (United Arab Emirates)': 'ar-AE',
    'Arabic (Yemen)': 'ar-YE',
    'Armenian (Armenia)': 'hy-AM',
    'Azerbaijani (Azerbaijan)': 'az-AZ',
    'Basque (Spain)': 'eu-ES',
    'Bengali (Bangladesh)': 'bn-BD',
    'Bengali (India)': 'bn-IN',
    'Bosnian (Bosnia and Herzegovina)': 'bs-BA',
    'Bulgarian (Bulgaria)': 'bg-BG',
    'Burmese (Myanmar)': 'my-MM',
    'Catalan (Spain)': 'ca-ES',
    'Chinese, Cantonese (Traditional Hong Kong)': 'yue-Hant-HK',
    'Chinese, Mandarin (Simplified, China)': 'zh (cmn-Hans-CN)',
    'Chinese, Mandarin (Traditional, Taiwan)': 'zh-TW (cmn-Hant-TW)',
    'Croatian (Croatia)': 'hr-HR',
    'Czech (Czech Republic)': 'cs-CZ',
    'Danish (Denmark)': 'da-DK',
    'Dutch (Belgium)': 'nl-BE',
    'Dutch (Netherlands)': 'nl-NL',
    'English (Australia)': 'en-AU',
    'English (Canada)': 'en-CA',
    'English (Ghana)': 'en-GH',
    'English (Hong Kong)': 'en-HK',
    'English (India)': 'en-IN',
    'English (Ireland)': 'en-IE',
    'English (Kenya)': 'en-KE',
    'English (New Zealand)': 'en-NZ',
    'English (Nigeria)': 'en-NG',
    'English (Pakistan)': 'en-PK',
    'English (Philippines)': 'en-PH',
    'English (Singapore)': 'en-SG',
    'English (South Africa)': 'en-ZA',
    'English (Tanzania)': 'en-TZ',
    'English (United Kingdom)': 'en-GB',
    'English (United States)': 'en-US',
    'Estonian (Estonia)': 'et-EE',
    'Filipino (Philippines)': 'fil-PH',
    'Finnish (Finland)': 'fi-FI',
    'French (Belgium)': 'fr-BE',
    'French (Canada)': 'fr-CA',
    'French (France)': 'fr-FR',
    'French (Switzerland)': 'fr-CH',
    'Galician (Spain)': 'gl-ES',
    'Georgian (Georgia)': 'ka-GE',
    'German (Austria)': 'de-AT',
    'German (Germany)': 'de-DE',
    'German (Switzerland)': 'de-CH',
    'Greek (Greece)': 'el-GR',
    'Gujarati (India)': 'gu-IN',
    'Hebrew (Israel)': 'iw-IL',
    'Hindi (India)': 'hi-IN',
    'Hungarian (Hungary)': 'hu-HU',
    'Icelandic (Iceland)': 'is-IS',
    'Indonesian (Indonesia)': 'id-ID',
    'Italian (Italy)': 'it-IT',
    'Italian (Switzerland)': 'it-CH',
    'Japanese (Japan)': 'ja-JP',
    'Javanese (Indonesia)': 'jv-ID',
    'Kannada (India)': 'kn-IN',
    'Kazakh (Kazakhstan)': 'kk-KZ',
    'Khmer (Cambodia)': 'km-KH',
    'Korean (South Korea)': 'ko-KR',
    'Lao (Laos)': 'lo-LA',
    'Latvian (Latvia)': 'lv-LV',
    'Lithuanian (Lithuania)': 'lt-LT',
    'Macedonian (North Macedonia)': 'mk-MK',
    'Malay (Malaysia)': 'ms-MY',
    'Malayalam (India)': 'ml-IN',
    'Marathi (India)': 'mr-IN',
    'Mongolian (Mongolia)': 'mn-MN',
    'Nepali (Nepal)': 'ne-NP',
    'Norwegian Bokmål (Norway)': 'no-NO',
    'Persian (Iran)': 'fa-IR',
    'Polish (Poland)': 'pl-PL',
    'Portuguese (Brazil)': 'pt-BR',
    'Portuguese (Portugal)': 'pt-PT',
    'Punjabi (Gurmukhi India)': 'pa-Guru-IN',
    'Romanian (Romania)': 'ro-RO',
    'Russian (Russia)': 'ru-RU',
    'Kinyarwanda (Rwanda)': 'rw-RW',
    'Serbian (Serbia)': 'sr-RS',
    'Sinhala (Sri Lanka)': 'si-LK',
    'Slovak (Slovakia)': 'sk-SK',
    'Slovenian (Slovenia)': 'sl-SI',
    'Swati (South Africa)': 'ss-latn-za',
    'Southern Sotho (South Africa)': 'st-ZA',
    'Spanish (Argentina)': 'es-AR',
    'Spanish (Bolivia)': 'es-BO',
    'Spanish (Chile)': 'es-CL',
    'Spanish (Colombia)': 'es-CO',
    'Spanish (Costa Rica)': 'es-CR',
    'Spanish (Dominican Republic)': 'es-DO',
    'Spanish (Ecuador)': 'es-EC',
    'Spanish (El Salvador)': 'es-SV',
    'Spanish (Guatemala)': 'es-GT',
    'Spanish (Honduras)': 'es-HN',
    'Spanish (Mexico)': 'es-MX',
    'Spanish (Nicaragua)': 'es-NI',
    'Spanish (Panama)': 'es-PA',
    'Spanish (Paraguay)': 'es-PY',
    'Spanish (Peru)': 'es-PE',
    'Spanish (Puerto Rico)': 'es-PR',
    'Spanish (Spain)': 'es-ES',
    'Spanish (United States)': 'es-US',
    'Spanish (Uruguay)': 'es-UY',
    'Spanish (Venezuela)': 'es-VE',
    'Sundanese (Indonesia)': 'su-ID',
    'Swahili (Kenya)': 'sw-KE',
    'Swahili (Tanzania)': 'sw-TZ',
    'Swedish (Sweden)': 'sv-SE',
    'Tamil (India)': 'ta-IN',
    'Tamil (Malaysia)': 'ta-MY',
    'Tamil (Singapore)': 'ta-SG',
    'Tamil (Sri Lanka)': 'ta-LK',
    'Telugu (India)': 'te-IN',
    'Thai (Thailand)': 'th-TH',
    'Setswana (South Africa)': 'tn-latn-za',
    'Turkish (Turkey)': 'tr-TR',
    'Tsonga (South Africa)': 'ts-ZA',
    'Ukrainian (Ukraine)': 'uk-UA',
    'Urdu (India)': 'ur-IN',
    'Urdu (Pakistan)': 'ur-PK',
    'Uzbek (Uzbekistan)': 'uz-UZ',
    'Venda (South Africa)': 've-ZA',
    'Vietnamese (Vietnam)': 'vi-VN',
    'isiXhosa (South Africa)': 'xh-ZA',
    'Zulu (South Africa)': 'zu-ZA',
}

export const textToSpeechLanguages: {[key: string]: string} = {
    'Afrikaans (South Africa)': 'af-ZA',
    'Arabic': 'ar-XA',
    'Basque (Spain)': 'eu-ES',
    'Bengali (India)': 'bn-IN',
    'Bulgarian (Bulgaria)': 'bg-BG',
    'Catalan (Spain)': 'ca-ES',
    'Chinese (Hong Kong)': 'yue-HK',
    'Czech (Czech Republic)': 'cs-CZ',
    'Danish (Denmark)': 'da-DK',
    'Dutch (Belgium)': 'nl-BE',
    'Dutch (Netherlands)': 'nl-NL',
    'English (Australia)': 'en-AU',
    'English (India)': 'en-IN',
    'English (UK)': 'en-GB',
    'English (US)': 'en-US',
    'Filipino (Philippines)': 'fil-PH',
    'Finnish (Finland)': 'fi-FI',
    'French (Canada)': 'fr-CA',
    'French (France)': 'fr-FR',
    'Galician (Spain)': 'gl-ES',
    'German (Germany)': 'de-DE',
    'Greek (Greece)': 'el-GR',
    'Gujarati (India)': 'gu-IN',
    'Hebrew (Israel)': 'he-IL',
    'Hindi (India)': 'hi-IN',
    'Hungarian (Hungary)': 'hu-HU',
    'Icelandic (Iceland)': 'is-IS',
    'Indonesian (Indonesia)': 'id-ID',
    'Italian (Italy)': 'it-IT',
    'Japanese (Japan)': 'ja-JP',
    'Kannada (India)': 'kn-IN',
    'Korean (South Korea)': 'ko-KR',
    'Latvian (Latvia)': 'lv-LV',
    'Lithuanian (Lithuania)': 'lt-LT',
    'Malay (Malaysia)': 'ms-MY',
    'Malayalam (India)': 'ml-IN',
    'Mandarin Chinese (China)': 'cmn-CN',
    'Mandarin Chinese (Taiwan)': 'cmn-TW',
    'Marathi (India)': 'mr-IN',
    'Norwegian (Norway)': 'nb-NO',
    'Polish (Poland)': 'pl-PL',
    'Portuguese (Brazil)': 'pt-BR',
    'Portuguese (Portugal)': 'pt-PT',
    'Punjabi (India)': 'pa-IN',
    'Romanian (Romania)': 'ro-RO',
    'Russian (Russia)': 'ru-RU',
    'Serbian (Cyrillic)': 'sr-RS',
    'Slovak (Slovakia)': 'sk-SK',
    'Spanish (Spain)': 'es-ES',
    'Spanish (US)': 'es-US',
    'Swedish (Sweden)': 'sv-SE',
    'Tamil (India)': 'ta-IN',
    'Telugu (India)': 'te-IN',
    'Thai (Thailand)': 'th-TH',
    'Turkish (Turkey)': 'tr-TR',
    'Ukrainian (Ukraine)': 'uk-UA',
    'Vietnamese (Vietnam)': 'vi-VN',
}

export const translationLanguages: {[key: string]: string} = {
    'Afrikaans': 'af',
    'Albanian': 'sq',
    'Amharic': 'am',
    'Arabic': 'ar',
    'Armenian': 'hy',
    'Assamese': 'as',
    'Aymara': 'ay',
    'Azerbaijani': 'az',
    'Bambara': 'bm',
    'Basque': 'eu',
    'Belarusian': 'be',
    'Bengali': 'bn',
    'Bhojpuri': 'bho',
    'Bosnian': 'bs',
    'Bulgarian': 'bg',
    'Catalan': 'ca',
    'Cebuano': 'ceb',
    'Chinese (Simplified)': 'zh-CN',
    'Chinese (Traditional)': 'zh-TW',
    'Corsican': 'co',
    'Croatian': 'hr',
    'Czech': 'cs',
    'Danish': 'da',
    'Dhivehi': 'dv',
    'Dogri': 'doi',
    'Dutch': 'nl',
    'English': 'en',
    'Esperanto': 'eo',
    'Estonian': 'et',
    'Ewe': 'ee',
    'Filipino (Tagalog)': 'fil',
    'Finnish': 'fi',
    'French': 'fr',
    'Frisian': 'fy',
    'Galician': 'gl',
    'Georgian': 'ka',
    'German': 'de',
    'Greek': 'el',
    'Guarani': 'gn',
    'Gujarati': 'gu',
    'Haitian Creole': 'ht',
    'Hausa': 'ha',
    'Hawaiian': 'haw',
    'Hebrew': 'he or iw',
    'Hindi': 'hi',
    'Hmong': 'hmn',
    'Hungarian': 'hu',
    'Icelandic': 'is',
    'Igbo': 'ig',
    'Ilocano': 'ilo',
    'Indonesian': 'id',
    'Irish': 'ga',
    'Italian': 'it',
    'Japanese': 'ja',
    'Javanese': 'jv',
    'Kannada': 'kn',
    'Kazakh': 'kk',
    'Khmer': 'km',
    'Kinyarwanda': 'rw',
    'Konkani': 'gom',
    'Korean': 'ko',
    'Krio': 'kri',
    'Kurdish': 'ku',
    'Kurdish (Sorani)': 'ckb',
    'Kyrgyz': 'ky',
    'Lao': 'lo',
    'Latin': 'la',
    'Latvian': 'lv',
    'Lingala': 'ln',
    'Lithuanian': 'lt',
    'Luganda': 'lg',
    'Luxembourgish': 'lb',
    'Macedonian': 'mk',
    'Maithili': 'mai',
    'Malagasy': 'mg',
    'Malay': 'ms',
    'Malayalam': 'ml',
    'Maltese': 'mt',
    'Maori': 'mi',
    'Marathi': 'mr',
    'Meiteilon (Manipuri)': 'mni-Mtei',
    'Mizo': 'lus',
    'Mongolian': 'mn',
    'Myanmar (Burmese)': 'my',
    'Nepali': 'ne',
    'Norwegian': 'no',
    'Nyanja (Chichewa)': 'ny',
    'Odia (Oriya)': 'or',
    'Oromo': 'om',
    'Pashto': 'ps',
    'Persian': 'fa',
    'Polish': 'pl',
    'Portuguese (Portugal, Brazil)': 'pt',
    'Punjabi': 'pa',
    'Quechua': 'qu',
    'Romanian': 'ro',
    'Russian': 'ru',
    'Samoan': 'sm',
    'Sanskrit': 'sa',
    'Scots Gaelic': 'gd',
    'Sepedi': 'nso',
    'Serbian': 'sr',
    'Sesotho': 'st',
    'Shona': 'sn',
    'Sindhi': 'sd',
    'Sinhala (Sinhalese)': 'si',
    'Slovak': 'sk',
    'Slovenian': 'sl',
    'Somali': 'so',
    'Spanish': 'es',
    'Sundanese': 'su',
    'Swahili': 'sw',
    'Swedish': 'sv',
    'Tagalog (Filipino)': 'tl',
    'Tajik': 'tg',
    'Tamil': 'ta',
    'Tatar': 'tt',
    'Telugu': 'te',
    'Thai': 'th',
    'Tigrinya': 'ti',
    'Tsonga': 'ts',
    'Turkish': 'tr',
    'Turkmen': 'tk',
    'Twi (Akan)': 'ak',
    'Ukrainian': 'uk',
    'Urdu': 'ur',
    'Uyghur': 'ug',
    'Uzbek': 'uz',
    'Vietnamese': 'vi',
    'Welsh': 'cy',
    'Xhosa': 'xh',
    'Yiddish': 'yi',
    'Yoruba': 'yo',
    'Zulu': 'zu',
}